[tool.poetry]
name = "teagurilla_embedder"
version = "0.1.0"
description = ""
authors = ["Petro Mozil <mozil.petryk@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
sentence-transformers = "^2.2.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
